name: Build & Release Gem to Github Packages
on:
  workflow_call:
    inputs:
      debug:
        description: "Enable SSH debugging"
        required: false
        default: false
        type: boolean
jobs:
  release_to_github_packages:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - if: ${{ inputs.debug }}
        name: Setup SSH session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: ncphillips,chrisdmacrae

      - name: Set Credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish to GitHub Packages
        run: |
          export OWNER=$( echo ${{ github.repository }} | cut -d "/" -f 1 )
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/pmfit/${OWNER} *.gem
          gem push *.gem